name: Gabs Flow!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
  show_date_job:
    runs-on: ubuntu-20.04
    steps:
      - name: Show Current Time
        run: date

